global:
  scrape_interval: 15s

scrape_configs:
  # Coleta métricas da própria API (logs de Erro/Sucesso que criamos)
  - job_name: 'fastapi-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:8000']

  # Coleta métricas da saúde do MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo-exporter:9216']