global:
  scrape_interval: 10s

scrape_configs:

  # ========== FastAPI ==========
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  # ========== PostgreSQL ==========
  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # ========== MongoDB ==========
  - job_name: "mongo-exporter"
    static_configs:
      - targets: ["mongo-exporter:9216"]

  # ========== Containers (cAdvisor) ==========
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # ========== Host (Node Exporter) ==========
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
